# Generated by Django 4.2.6 on 2023-10-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_comment_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
    ]
