# Generated by Django 4.2.6 on 2023-10-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',)},
        ),
    ]
